name: Build
on:
  push:
    branches:
      - 'master'
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build
    permissions:
      id-token: write
      contents: write
      attestations: write
    needs: tag
    uses: ./.github/workflows/pyinstaller.yml
    with:
      file: main.py
      name: allslain
      icon: icon/ded.ico
      output: dist/allslain.exe
      attest: false
      prerelease: true
  build_gui:
    runs-on: ubuntu-latest
    permissions: {}
    needs: tag
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: build
          repository: DimmaDont/all-slain-gui
          token: ${{ secrets.ASDF }}
