name: Build
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build
    permissions:
      id-token: write
      contents: write
      attestations: write
    uses: ./.github/workflows/pyinstaller.yml
    with:
      file: main.py
      name: allslain
      icon: icon/ded.ico
      output: dist/allslain.exe
      attest: false
      release: true
      tag_name: latest
