name: Package
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
      - name: Install dependencies
        shell: bash
        run: pip install build
      - name: Build
        shell: bash
        run: python -m build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
