name: Build-PyInstaller
on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: windows-latest
      python-version:
        required: false
        type: string
        default: 3.x
      file:
        required: true
        type: string
      name:
        required: true
        type: string
      icon:
        required: true
        type: string
      output:
        required: true
        type: string
      attest:
        required: false
        type: boolean
        default: false
      prerelease:
        required: false
        type: boolean
        default: false
jobs:
  build:
    name: PyInstaller
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
          architecture: x64
          cache: pip
      - name: Install Dependencies
        run: pip install -e .[build_app]
      - name: Package Application
        run: pyinstaller --onefile ${{ inputs.file }} --name ${{ inputs.name }} --icon ${{ inputs.icon }} --noupx --debug noarchive --exclude-module pkg_resources
      - name: Attest
        id: attest
        uses: actions/attest-build-provenance@v3
        if: ${{ inputs.attest }}
        with:
          subject-path: ${{ github.workspace }}/dist
      - name: Get file hash
        shell: pwsh
        id: hash
        run: |
          "file_hash=$((Get-FileHash ${{ inputs.output }}).Hash.ToLower())" >> $env:GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: ${{ inputs.output }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body: |
            **Attestation**: [`${{ steps.attest.outputs.attestation-id }}`](${{ steps.attest.outputs.attestation-url }})
            **VirusTotal**: [`${{ steps.hash.outputs.file_hash }}`](https://www.virustotal.com/gui/file/${{ steps.hash.outputs.file_hash }})
          files: ${{ inputs.output }}
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }}
