name: Build-PyInstaller
on: [push]
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:

      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        shell: bash
        run: |
          pip install pyinstaller

      - name: Package Application
        shell: bash
        run: |
          pyinstaller --onefile allslain.py --icon icon/ded.ico

      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: '${{ github.workspace }}/dist'

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: dist/allslain.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/allslain.exe
