name: Build-PyInstaller
on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: windows-latest
      python-version:
        required: false
        type: string
        default: 3.x
      file:
        required: true
        type: string
      icon:
        required: true
        type: string
      output:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ inputs.os }}
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          architecture: x64
          cache: pip
      - name: Install Dependencies
        shell: bash
        run: |
          pip install pyinstaller
      - name: Package Application
        shell: bash
        run: |
          pyinstaller --onefile ${{ inputs.file }} --icon ${{ inputs.icon }}
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ github.workspace }}/dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: ${{ inputs.output }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ inputs.output }}
