name: Release
on:
  release:
    types: [published]
jobs:
  build:
    name: Build and release
    permissions:
      attestations: write
      contents: write
      id-token: write
    uses: ./.github/workflows/pyinstaller.yml
    with:
      file: main.py
      name: allslain
      icon: icon/ded.ico
      output: dist/allslain.exe
      attest: true
      prerelease: false
